export const blockList = [
  "mailinator.com",
  "yopmail.com",
  "guerrillamail.com",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co.uk",
  "10minutemail.org",
  "tempmail.com",
  "tempmailo.com",
  "tempmail.net",
  "tempmail.plus",
  "temp-mail.io",
  "tempmail.lol",
  "tempmail.xyz",
  "tempemail.co",
  "tempinbox.xyz",
  "tempmailgen.com",
  "temp-mail.org",

  "getnada.com",
  "getairmail.com",
  "dropmail.me",
  "maildrop.cc",
  "trashmail.com",
  "trashmail.de",
  "fakemail.net",
  "fakemailgenerator.com",
  "emailtemporario.com",
  "emailondeck.com",
  "mailnesia.com",
  "mailcatch.com",
  "moakt.com",
  "bareed.ws",
  "mail7.io",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spamgourmet.com",
  "spamex.com",

  "mail1a.de",
  "sharklasers.com",
  "guerrillamailblock.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.pl",

  "cock.email",
  "lroid.com",
  "mytemp.email",
  "mytrashmail.com",
  "trashmail.ws",
  "fakeinbox.com",
  "fakebox.org",
  "anonmail.top",
  "inboxbear.com",
  "instantemailaddress.com",
  "inboxes.com",

  "owlymail.com",
  "tmail.ws",
  "tmails.net",
  "mail-temp.com",
  "spam4.me",
  "soombo.com",
  "dropjar.com",
  "xojxe.com",
  "buytempmail.com",
  "speedmail.now",
  "coolmail.fun",

  "datehype.com",
  "ishyp.com",
  "jawillmake.com",
  "spoty.email",
  "spotymail.com",
  "skzmail.com",
  "skzmail.xyz",

  "tmpmail.net",
  "tmpmail.org",
  "tmpbox.net",
  "steam-mail.com",
  "supracraft.net",
  "duam.net",

  "spamdecoy.net",
  "spamfree24.org",
  "spamfree24.net",
  "mailnull.com",
  "throwawaymail.com",
  "nowmymail.com",

  "relay.firemail.wtf",
  "nada.email",
  "nothingtohide.nl",
  "mutantmail.com",
  "trashmail.io",
  "keemail.me",
  "trymail.tk",

  "hmail.us",
  "spamhereplease.com",
  "spammail.me",
  "mailtrix.net",
  "mailsac.com",
  "fastmailforyou.net",

  "mailtemp.info",
  "alivance.com",
  "mailhub24.com",
  "emlpro.com",
  "dmailify.com",
  "meltmail.com",

  "mail1.me",
  "mailpoof.com",
  "mailtome.de",
  "testmail.app",
  "tempcloudmail.com",
];
